### ISSUE TITLE
Usage guide?

### ISSUE THREAD

**Issue by musjj** [TechnocatDev/2d-shapes#4]
Any guide on how to use this? I'm not really sure how you're supposed to get the node tree shown in the screenshot.

Some help would be appreciated :)

**Comment by musjj** [comment]
Oh never mind, you just need to enable the plugin in the project settings first: https://docs.godotengine.org/en/stable/tutorials/plugins/editor/installing_plugins.html#enabling-a-plugin

Then the shapes should show up in the "Add Child Node..." menu.

**Comment by Dener-Silva** [comment]
No worries, I've made the same mistake before 😅
